module UserDisplayNameGenerator
  # https://fluentemoji.com/

  ADJECTIVES = %w[
    Adventurous Agile Amber Ancient Artful Astonishing Audacious Autumn Azure
    Balanced Bashful Bold Bouncy Brave Bright Brilliant Calm Caring Cheerful Clever
    Cloudy Cozy Curious Daring Dazzling Diligent Dreamy Eager Elegant Enchanted
    Energetic Fair Fearless Festive Fierce Fluffy Fortunate Friendly Gentle
    Glimmering Gleaming Graceful Grateful Happy Harmonious Heroic Honest Hopeful
    Humble Jolly Joyful Kind Lively Lucky Luminous Magical Merry Mighty Mindful
    Misty Modest Noble Optimistic Peaceful Playful Pleasant Polite Powerful Pristine
    Proud Quick Quiet Radiant Ready Regal Relaxed Remarkable Resilient Respectful
    Roaring Rosy Royal Sassy Serene Shimmering Shiny Silky Sincere Skillful Sleepy
    Smart Snappy Sociable Soft Sparkling Spirited Splendid Steady Sunny Swift
    Tender Thoughtful Tiny Tranquil Trusty Valiant Vibrant Victorious Warm Whimsical
    Wise Witty Wonderful Zany Zealous Zesty Abundant Breezy Brisk Charming Colorful
    Dapper Dewy Dynamic Enthusiastic Glorious Inspiring Inventive Loyal Mellow
    Mysterious Nimble Plucky Quirky Rejoicing Shy Sleek Spunky Starlit Upbeat
    Vivacious Wandering Watchful Welcoming Whistling Youthful
  ]

  ANIMAL_AND_NATURE_IMAGE_PATHS_BY_NOUN = {
    "Raccoon" => "emoji/animals_and_nature/raccoon_3d.png",
    "Tiger" => "emoji/animals_and_nature/tiger_face_3d.png",
    "Fox" => "emoji/animals_and_nature/fox_3d.png",
    "Panda" => "emoji/animals_and_nature/panda_3d.png",
    "Cat" => "emoji/animals_and_nature/cat_face_3d.png",
    "Koala" => "emoji/animals_and_nature/koala_3d.png",
    "Rabbit" => "emoji/animals_and_nature/rabbit_face_3d.png",
    "Lion" => "emoji/animals_and_nature/lion_3d.png",
    "Dog" => "emoji/animals_and_nature/dog_face_3d.png",
    "Bear" => "emoji/animals_and_nature/bear_3d.png",
    "Polar Bear" => "emoji/animals_and_nature/polar_bear_3d.png",
    "Wolf" => "emoji/animals_and_nature/wolf_3d.png",
    "Leopard" => "emoji/animals_and_nature/leopard_3d.png",
    "Deer" => "emoji/animals_and_nature/deer_3d.png",
    "Horse" => "emoji/animals_and_nature/horse_face_3d.png",
    "Zebra" => "emoji/animals_and_nature/zebra_3d.png",
    "Giraffe" => "emoji/animals_and_nature/giraffe_3d.png",
    "Elephant" => "emoji/animals_and_nature/elephant_3d.png",
    "Mammoth" => "emoji/animals_and_nature/mammoth_3d.png",
    "Rhino" => "emoji/animals_and_nature/rhinoceros_3d.png",
    "Hippo" => "emoji/animals_and_nature/hippopotamus_3d.png",
    "Cow" => "emoji/animals_and_nature/cow_face_3d.png",
    "Pig" => "emoji/animals_and_nature/pig_face_3d.png",
    "Goat" => "emoji/animals_and_nature/goat_3d.png",
    "Sheep" => "emoji/animals_and_nature/ewe_3d.png",
    "Monkey" => "emoji/animals_and_nature/monkey_3d.png",
    "Gorilla" => "emoji/animals_and_nature/gorilla_3d.png",
    "Orangutan" => "emoji/animals_and_nature/orangutan_3d.png",
    "Sloth" => "emoji/animals_and_nature/sloth_3d.png",
    "Otter" => "emoji/animals_and_nature/otter_3d.png",
    "Beaver" => "emoji/animals_and_nature/beaver_3d.png",
    "Mouse" => "emoji/animals_and_nature/mouse_face_3d.png",
    "Hamster" => "emoji/animals_and_nature/hamster_3d.png",
    "Hedgehog" => "emoji/animals_and_nature/hedgehog_3d.png",
    "Bat" => "emoji/animals_and_nature/bat_3d.png",
    "Owl" => "emoji/animals_and_nature/owl_3d.png",
    "Eagle" => "emoji/animals_and_nature/eagle_3d.png",
    "Parrot" => "emoji/animals_and_nature/parrot_3d.png",
    "Penguin" => "emoji/animals_and_nature/penguin_3d.png",
    "Flamingo" => "emoji/animals_and_nature/flamingo_3d.png",
    "Swan" => "emoji/animals_and_nature/swan_3d.png",
    "Duck" => "emoji/animals_and_nature/duck_3d.png",
    "Chicken" => "emoji/animals_and_nature/chicken_3d.png",
    "Rooster" => "emoji/animals_and_nature/rooster_3d.png",
    "Turkey" => "emoji/animals_and_nature/turkey_3d.png",
    "Peacock" => "emoji/animals_and_nature/peacock_3d.png",
    "Fish" => "emoji/animals_and_nature/fish_3d.png",
    "Dolphin" => "emoji/animals_and_nature/dolphin_3d.png",
    "Whale" => "emoji/animals_and_nature/whale_3d.png",
    "Shark" => "emoji/animals_and_nature/shark_3d.png",
    "Octopus" => "emoji/animals_and_nature/octopus_3d.png",
    "Turtle" => "emoji/animals_and_nature/turtle_3d.png",
    "Crocodile" => "emoji/animals_and_nature/crocodile_3d.png",
    "Snake" => "emoji/animals_and_nature/snake_3d.png",
    "Lizard" => "emoji/animals_and_nature/lizard_3d.png",
    "Frog" => "emoji/animals_and_nature/frog_3d.png",
    "Butterfly" => "emoji/animals_and_nature/butterfly_3d.png",
    "Bee" => "emoji/animals_and_nature/honeybee_3d.png",
    "Ladybug" => "emoji/animals_and_nature/lady_beetle_3d.png",
    "Ant" => "emoji/animals_and_nature/ant_3d.png",
    "Snail" => "emoji/animals_and_nature/snail_3d.png",
    "Spider" => "emoji/animals_and_nature/spider_3d.png",
    "Baby Chick" => "emoji/animals_and_nature/baby_chick_3d.png",
    "Badger" => "emoji/animals_and_nature/badger_3d.png",
    "Beetle" => "emoji/animals_and_nature/beetle_3d.png",
    "Bird" => "emoji/animals_and_nature/bird_3d.png",
    "Bison" => "emoji/animals_and_nature/bison_3d.png",
    "Black Cat" => "emoji/animals_and_nature/black_cat_3d.png",
    "Black Bird" => "emoji/animals_and_nature/blackbird_3d.png",
    "Blossom" => "emoji/animals_and_nature/blossom_3d.png",
    "Blowfish" => "emoji/animals_and_nature/blowfish_3d.png",
    "Boar" => "emoji/animals_and_nature/boar_3d.png",
    "Bouquet" => "emoji/animals_and_nature/bouquet_3d.png",
    "Bug" => "emoji/animals_and_nature/bug_3d.png",
    "Cactus" => "emoji/animals_and_nature/cactus_3d.png",
    "Camel" => "emoji/animals_and_nature/camel_3d.png",
    "Cat Body" => "emoji/animals_and_nature/cat_3d.png",
    "Cherry Blossom" => "emoji/animals_and_nature/cherry_blossom_3d.png",
    "Chipmunk" => "emoji/animals_and_nature/chipmunk_3d.png",
    "Cockroach" => "emoji/animals_and_nature/cockroach_3d.png",
    "Coral" => "emoji/animals_and_nature/coral_3d.png",
    "Cow Body" => "emoji/animals_and_nature/cow_3d.png",
    "Cricket" => "emoji/animals_and_nature/cricket_3d.png",
    "Deciduous Tree" => "emoji/animals_and_nature/deciduous_tree_3d.png",
    "Dodo" => "emoji/animals_and_nature/dodo_3d.png",
    "Dog Body" => "emoji/animals_and_nature/dog_3d.png",
    "Donkey" => "emoji/animals_and_nature/donkey_3d.png",
    "Dove" => "emoji/animals_and_nature/dove_3d.png",
    "Dragon Face" => "emoji/animals_and_nature/dragon_face_3d.png",
    "Dragon" => "emoji/animals_and_nature/dragon_3d.png",
    "Empty Nest" => "emoji/animals_and_nature/empty_nest_3d.png",
    "Evergreen Tree" => "emoji/animals_and_nature/evergreen_tree_3d.png",
    "Fallen Leaf" => "emoji/animals_and_nature/fallen_leaf_3d.png",
    "Feather" => "emoji/animals_and_nature/feather_3d.png",
    "Fly" => "emoji/animals_and_nature/fly_3d.png",
    "Four Leaf Clover" => "emoji/animals_and_nature/four_leaf_clover_3d.png",
    "Front-Facing Baby Chick" => "emoji/animals_and_nature/front-facing_baby_chick_3d.png",
    "Goose" => "emoji/animals_and_nature/goose_3d.png",
    "Guide Dog" => "emoji/animals_and_nature/guide_dog_3d.png",
    "Hatching Chick" => "emoji/animals_and_nature/hatching_chick_3d.png",
    "Herb" => "emoji/animals_and_nature/herb_3d.png",
    "Hibiscus" => "emoji/animals_and_nature/hibiscus_3d.png",
    "Galloping Horse" => "emoji/animals_and_nature/horse_3d.png",
    "Hyacinth" => "emoji/animals_and_nature/hyacinth_3d.png",
    "Jellyfish" => "emoji/animals_and_nature/jellyfish_3d.png",
    "Kangaroo" => "emoji/animals_and_nature/kangaroo_3d.png",
    "Leaf Fluttering In Wind" => "emoji/animals_and_nature/leaf_fluttering_in_wind_3d.png",
    "Llama" => "emoji/animals_and_nature/llama_3d.png",
    "Lotus" => "emoji/animals_and_nature/lotus_3d.png",
    "Maple Leaf" => "emoji/animals_and_nature/maple_leaf_3d.png",
    "Microbe" => "emoji/animals_and_nature/microbe_3d.png",
    "Monkey Face" => "emoji/animals_and_nature/monkey_face_3d.png",
    "Moose" => "emoji/animals_and_nature/moose_3d.png",
    "Mosquito" => "emoji/animals_and_nature/mosquito_3d.png",
    "Mouse Body" => "emoji/animals_and_nature/mouse_3d.png",
    "Nest With Eggs" => "emoji/animals_and_nature/nest_with_eggs_3d.png",
    "Ox" => "emoji/animals_and_nature/ox_3d.png",
    "Palm Tree" => "emoji/animals_and_nature/palm_tree_3d.png",
    "Paw Prints" => "emoji/animals_and_nature/paw_prints_3d.png",
    "Phoenix" => "emoji/animals_and_nature/phoenix_bird_3d.png",
    "Pig Nose" => "emoji/animals_and_nature/pig_nose_3d.png",
    "Pig Body" => "emoji/animals_and_nature/pig_3d.png",
    "Poodle" => "emoji/animals_and_nature/poodle_3d.png",
    "Potted Plant" => "emoji/animals_and_nature/potted_plant_3d.png",
    "Rabbit Body" => "emoji/animals_and_nature/rabbit_3d.png",
    "Ram" => "emoji/animals_and_nature/ram_3d.png",
    "Rat" => "emoji/animals_and_nature/rat_3d.png",
    "Rose" => "emoji/animals_and_nature/rose_3d.png",
    "Rosette" => "emoji/animals_and_nature/rosette_3d.png",
    "Sauropod" => "emoji/animals_and_nature/sauropod_3d.png",
    "Scorpion" => "emoji/animals_and_nature/scorpion_3d.png",
    "Seal" => "emoji/animals_and_nature/seal_3d.png",
    "Seedling" => "emoji/animals_and_nature/seedling_3d.png",
    "Service Dog" => "emoji/animals_and_nature/service_dog_3d.png",
    "Shamrock" => "emoji/animals_and_nature/shamrock_3d.png",
    "Sheaf Of Rice" => "emoji/animals_and_nature/sheaf_of_rice_3d.png",
    "Skunk" => "emoji/animals_and_nature/skunk_3d.png",
    "Spider Web" => "emoji/animals_and_nature/spider_web_3d.png",
    "Spiral Shell" => "emoji/animals_and_nature/spiral_shell_3d.png",
    "Spouting Whale" => "emoji/animals_and_nature/spouting_whale_3d.png",
    "Sunflower" => "emoji/animals_and_nature/sunflower_3d.png",
    "T-Rex" => "emoji/animals_and_nature/t-rex_3d.png",
    "Tiger Body" => "emoji/animals_and_nature/tiger_3d.png",
    "Tropical Fish" => "emoji/animals_and_nature/tropical_fish_3d.png",
    "Tulip" => "emoji/animals_and_nature/tulip_3d.png",
    "Two-Hump Camel" => "emoji/animals_and_nature/two-hump_camel_3d.png",
    "Unicorn" => "emoji/animals_and_nature/unicorn_3d.png",
    "Water Buffalo" => "emoji/animals_and_nature/water_buffalo_3d.png",
    "White Flower" => "emoji/animals_and_nature/white_flower_3d.png",
    "Wilted Flower" => "emoji/animals_and_nature/wilted_flower_3d.png",
    "Wing" => "emoji/animals_and_nature/wing_3d.png",
    "Worm" => "emoji/animals_and_nature/worm_3d.png"
  }

  FOOD_AND_DRINK_IMAGE_PATHS_BY_NOUN = {
    "Crab" => "emoji/food_and_drink/crab_3d.png",
    "Lobster" => "emoji/food_and_drink/lobster_3d.png",
    "Shrimp" => "emoji/food_and_drink/shrimp_3d.png",
    "Amphora" => "emoji/food_and_drink/amphora_3d.png",
    "Avocado" => "emoji/food_and_drink/avocado_3d.png",
    "Baby Bottle" => "emoji/food_and_drink/baby_bottle_3d.png",
    "Bacon" => "emoji/food_and_drink/bacon_3d.png",
    "Bagel" => "emoji/food_and_drink/bagel_3d.png",
    "Baguette Bread" => "emoji/food_and_drink/baguette_bread_3d.png",
    "Banana" => "emoji/food_and_drink/banana_3d.png",
    "Beans" => "emoji/food_and_drink/beans_3d.png",
    "Beer Mug" => "emoji/food_and_drink/beer_mug_3d.png",
    "Bell Pepper" => "emoji/food_and_drink/bell_pepper_3d.png",
    "Bento Box" => "emoji/food_and_drink/bento_box_3d.png",
    "Beverage Box" => "emoji/food_and_drink/beverage_box_3d.png",
    "Birthday Cake" => "emoji/food_and_drink/birthday_cake_3d.png",
    "Blueberries" => "emoji/food_and_drink/blueberries_3d.png",
    "Bottle With Popping Cork" => "emoji/food_and_drink/bottle_with_popping_cork_3d.png",
    "Bowl With Spoon" => "emoji/food_and_drink/bowl_with_spoon_3d.png",
    "Bread" => "emoji/food_and_drink/bread_3d.png",
    "Broccoli" => "emoji/food_and_drink/broccoli_3d.png",
    "Brown Mushroom" => "emoji/food_and_drink/brown_mushroom_3d.png",
    "Bubble Tea" => "emoji/food_and_drink/bubble_tea_3d.png",
    "Burrito" => "emoji/food_and_drink/burrito_3d.png",
    "Butter" => "emoji/food_and_drink/butter_3d.png",
    "Candy" => "emoji/food_and_drink/candy_3d.png",
    "Canned Food" => "emoji/food_and_drink/canned_food_3d.png",
    "Carrot" => "emoji/food_and_drink/carrot_3d.png",
    "Cheese Wedge" => "emoji/food_and_drink/cheese_wedge_3d.png",
    "Cherries" => "emoji/food_and_drink/cherries_3d.png",
    "Chestnut" => "emoji/food_and_drink/chestnut_3d.png",
    "Chocolate Bar" => "emoji/food_and_drink/chocolate_bar_3d.png",
    "Chopsticks" => "emoji/food_and_drink/chopsticks_3d.png",
    "Clinking Beer Mugs" => "emoji/food_and_drink/clinking_beer_mugs_3d.png",
    "Clinking Glasses" => "emoji/food_and_drink/clinking_glasses_3d.png",
    "Cocktail Glass" => "emoji/food_and_drink/cocktail_glass_3d.png",
    "Coconut" => "emoji/food_and_drink/coconut_3d.png",
    "Cooked Rice" => "emoji/food_and_drink/cooked_rice_3d.png",
    "Cookie" => "emoji/food_and_drink/cookie_3d.png",
    "Cooking" => "emoji/food_and_drink/cooking_3d.png",
    "Croissant" => "emoji/food_and_drink/croissant_3d.png",
    "Cucumber" => "emoji/food_and_drink/cucumber_3d.png",
    "Cup With Straw" => "emoji/food_and_drink/cup_with_straw_3d.png",
    "Cupcake" => "emoji/food_and_drink/cupcake_3d.png",
    "Curry Rice" => "emoji/food_and_drink/curry_rice_3d.png",
    "Custard" => "emoji/food_and_drink/custard_3d.png",
    "Cut Of Meat" => "emoji/food_and_drink/cut_of_meat_3d.png",
    "Dango" => "emoji/food_and_drink/dango_3d.png",
    "Doughnut" => "emoji/food_and_drink/doughnut_3d.png",
    "Dumpling" => "emoji/food_and_drink/dumpling_3d.png",
    "Ear Of Corn" => "emoji/food_and_drink/ear_of_corn_3d.png",
    "Egg" => "emoji/food_and_drink/egg_3d.png",
    "Eggplant" => "emoji/food_and_drink/eggplant_3d.png",
    "Falafel" => "emoji/food_and_drink/falafel_3d.png",
    "Fish Cake With Swirl" => "emoji/food_and_drink/fish_cake_with_swirl_3d.png",
    "Flatbread" => "emoji/food_and_drink/flatbread_3d.png",
    "Fondue" => "emoji/food_and_drink/fondue_3d.png",
    "Fork And Knife With Plate" => "emoji/food_and_drink/fork_and_knife_with_plate_3d.png",
    "Fork And Knife" => "emoji/food_and_drink/fork_and_knife_3d.png",
    "Fortune Cookie" => "emoji/food_and_drink/fortune_cookie_3d.png",
    "French Fries" => "emoji/food_and_drink/french_fries_3d.png",
    "Fried Shrimp" => "emoji/food_and_drink/fried_shrimp_3d.png",
    "Garlic" => "emoji/food_and_drink/garlic_3d.png",
    "Ginger Root" => "emoji/food_and_drink/ginger_root_3d.png",
    "Glass Of Milk" => "emoji/food_and_drink/glass_of_milk_3d.png",
    "Grapes" => "emoji/food_and_drink/grapes_3d.png",
    "Green Apple" => "emoji/food_and_drink/green_apple_3d.png",
    "Green Salad" => "emoji/food_and_drink/green_salad_3d.png",
    "Hamburger" => "emoji/food_and_drink/hamburger_3d.png",
    "Honey Pot" => "emoji/food_and_drink/honey_pot_3d.png",
    "Hot Beverage" => "emoji/food_and_drink/hot_beverage_3d.png",
    "Hot Dog" => "emoji/food_and_drink/hot_dog_3d.png",
    "Hot Pepper" => "emoji/food_and_drink/hot_pepper_3d.png",
    "Ice Cream" => "emoji/food_and_drink/ice_cream_3d.png",
    "Ice" => "emoji/food_and_drink/ice_3d.png",
    "Jar" => "emoji/food_and_drink/jar_3d.png",
    "Kitchen Knife" => "emoji/food_and_drink/kitchen_knife_3d.png",
    "Kiwi Fruit" => "emoji/food_and_drink/kiwi_fruit_3d.png",
    "Leafy Green" => "emoji/food_and_drink/leafy_green_3d.png",
    "Lemon" => "emoji/food_and_drink/lemon_3d.png",
    "Lime" => "emoji/food_and_drink/lime_3d.png",
    "Lollipop" => "emoji/food_and_drink/lollipop_3d.png",
    "Mango" => "emoji/food_and_drink/mango_3d.png",
    "Mate" => "emoji/food_and_drink/mate_3d.png",
    "Meat On Bone" => "emoji/food_and_drink/meat_on_bone_3d.png",
    "Melon" => "emoji/food_and_drink/melon_3d.png",
    "Moon Cake" => "emoji/food_and_drink/moon_cake_3d.png",
    "Mushroom" => "emoji/food_and_drink/mushroom_3d.png",
    "Oden" => "emoji/food_and_drink/oden_3d.png",
    "Olive" => "emoji/food_and_drink/olive_3d.png",
    "Onion" => "emoji/food_and_drink/onion_3d.png",
    "Oyster" => "emoji/food_and_drink/oyster_3d.png",
    "Pancakes" => "emoji/food_and_drink/pancakes_3d.png",
    "Pea Pod" => "emoji/food_and_drink/pea_pod_3d.png",
    "Peach" => "emoji/food_and_drink/peach_3d.png",
    "Peanuts" => "emoji/food_and_drink/peanuts_3d.png",
    "Pear" => "emoji/food_and_drink/pear_3d.png",
    "Pie" => "emoji/food_and_drink/pie_3d.png",
    "Pineapple" => "emoji/food_and_drink/pineapple_3d.png",
    "Pizza" => "emoji/food_and_drink/pizza_3d.png",
    "Popcorn" => "emoji/food_and_drink/popcorn_3d.png",
    "Pot Of Food" => "emoji/food_and_drink/pot_of_food_3d.png",
    "Potato" => "emoji/food_and_drink/potato_3d.png",
    "Poultry Leg" => "emoji/food_and_drink/poultry_leg_3d.png",
    "Pouring Liquid" => "emoji/food_and_drink/pouring_liquid_3d.png",
    "Pretzel" => "emoji/food_and_drink/pretzel_3d.png",
    "Red Apple" => "emoji/food_and_drink/red_apple_3d.png",
    "Rice Ball" => "emoji/food_and_drink/rice_ball_3d.png",
    "Rice Cracker" => "emoji/food_and_drink/rice_cracker_3d.png",
    "Roasted Sweet Potato" => "emoji/food_and_drink/roasted_sweet_potato_3d.png",
    "Sake" => "emoji/food_and_drink/sake_3d.png",
    "Salt" => "emoji/food_and_drink/salt_3d.png",
    "Sandwich" => "emoji/food_and_drink/sandwich_3d.png",
    "Shallow Pan Of Food" => "emoji/food_and_drink/shallow_pan_of_food_3d.png",
    "Shaved Ice" => "emoji/food_and_drink/shaved_ice_3d.png",
    "Shortcake" => "emoji/food_and_drink/shortcake_3d.png",
    "Soft Ice Cream" => "emoji/food_and_drink/soft_ice_cream_3d.png",
    "Spaghetti" => "emoji/food_and_drink/spaghetti_3d.png",
    "Spoon" => "emoji/food_and_drink/spoon_3d.png",
    "Squid" => "emoji/food_and_drink/squid_3d.png",
    "Steaming Bowl" => "emoji/food_and_drink/steaming_bowl_3d.png",
    "Strawberry" => "emoji/food_and_drink/strawberry_3d.png",
    "Stuffed Flatbread" => "emoji/food_and_drink/stuffed_flatbread_3d.png",
    "Sushi" => "emoji/food_and_drink/sushi_3d.png",
    "Taco" => "emoji/food_and_drink/taco_3d.png",
    "Takeout Box" => "emoji/food_and_drink/takeout_box_3d.png",
    "Tamale" => "emoji/food_and_drink/tamale_3d.png",
    "Tangerine" => "emoji/food_and_drink/tangerine_3d.png",
    "Teacup Without Handle" => "emoji/food_and_drink/teacup_without_handle_3d.png",
    "Teapot" => "emoji/food_and_drink/teapot_3d.png",
    "Tomato" => "emoji/food_and_drink/tomato_3d.png",
    "Tropical Drink" => "emoji/food_and_drink/tropical_drink_3d.png",
    "Tumbler Glass" => "emoji/food_and_drink/tumbler_glass_3d.png",
    "Waffle" => "emoji/food_and_drink/waffle_3d.png",
    "Watermelon" => "emoji/food_and_drink/watermelon_3d.png",
    "Wine Glass" => "emoji/food_and_drink/wine_glass_3d.png"
  }

  ALL_IMAGE_PATHS_BY_NOUN = [
    ANIMAL_AND_NATURE_IMAGE_PATHS_BY_NOUN,
    FOOD_AND_DRINK_IMAGE_PATHS_BY_NOUN
  ].reduce({}, :merge)

  NOUNS = ALL_IMAGE_PATHS_BY_NOUN.keys
  IMAGE_PATHS = ALL_IMAGE_PATHS_BY_NOUN.values

  class << self
    def image_path_for(display_name)
      noun = display_name.split(" ", 2).last.sub(/ \d+\z/, "")
      ALL_IMAGE_PATHS_BY_NOUN.fetch(noun)
    end

    def display_name
      base_name = "#{ADJECTIVES.sample} #{NOUNS.sample}"
      candidate_name = base_name
      number = 2

      while User.exists?(display_name: candidate_name)
        candidate_name = "#{base_name} #{number}"
        number += 1
      end

      candidate_name
    end
  end
end
